### ISSUE TITLE
RetainWrapper in work

### ISSUE THREAD

**Issue by crysan** [rovkinmax/RxRetainFragment#3]
Hi!
How to check that RetainWrapper work?
If you minimize the application and then deploy it ceases to update the ProgressBar, until you turn the screen.

**Comment by rovkinmax** [comment]
see [tests](https://github.com/rovkinmax/RxRetainFragment/blob/master/app/src/androidTest/java/com/github/rovkinmax/rxretainexample/RotationActivityTest.kt) :) they cover this case
or just believe that it work correct

**Comment by crysan** [comment]
And to make something simple as possible?
For example:
`if (RetainWrapper.isrunning()) 
     RetainWrapper.restart();`

**Comment by rovkinmax** [comment]
may be in future :)

**Comment by crysan** [comment]
It's a pity.
The long-term development which left very little to the masterpiece.
