### ISSUE TITLE
in Fragment

### ISSUE THREAD

**Issue by crysan** [rovkinmax/RxRetainFragment#4]
Hi!
How to use RetainFactory.create in a fragment?
It seems that getFragmentManager () again displays the fragment.  The same fragment is displayed twice.

**Comment by rovkinmax** [comment]
nope, its invisible fragment. if in doubt, use `getActivity().getFragmentManager()`

**Comment by crysan** [comment]
I Tried.  Does not help.

**Comment by crysan** [comment]
There are ideas?

**Comment by rovkinmax** [comment]
Okey, I check it

**Comment by crysan** [comment]
The problem was solved when getFragmentManager() replace on getSupportFragmentManager().
Ty!
